### PR TITLE
Fix missing kwarg in MetaPMLBuilder package method

### PR DESCRIPTION
**Pull request by cpoisson**
This PR intends to fix https://github.com/aldebaran/qibuild/issues/111

### CODE REVIEW

**Comment by cpoisson** [comment]
Rebased on the IPython fix to show that it completely fix the build with this patch.

It seems to have created a brand new commit, it's my first PRs. Hope it will not conflict with #112

**Comment by vbarbaresi** [comment]
you can rebase, remove the commit and push -f on your fork. It will edit the PR

**Comment by cpoisson** [comment]
Done

**Comment by cpoisson** [comment]
@BallaMatt03 

This PR might interest you, if you want the unit tests to be fixed.

**Comment by cpoisson** [comment]
Dropping this one.

**Pull request closed without merging**
